In [1]:
# import numpy
import numpy as np


In [2]:
# array creation 
a=np.array([2,3,4])
a

array([2, 3, 4])

In [3]:
print(a)

[2 3 4]


In [5]:
# array type
a.dtype

dtype('int64')

In [6]:
type(a)

numpy.ndarray

In [10]:
#we can pass float number also 
#b=np.array([1.2,3.4,6.8,9],dtype=int)
b=np.array([1.2,3.4,6.8])
b

array([1.2, 3.4, 6.8])

In [11]:
print(b)

[1.2 3.4 6.8]


In [13]:
b.dtype

dtype('float64')

In [15]:
# Array Transform Sequence 
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#help(np.array)
c.ndim

2

In [24]:
d=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [25]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
d.ndim

2

In [27]:
#At the time of array creation we can give data type as well 
e=np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=complex)

In [28]:
e

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [31]:
f=np.zeros((4,5))
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
f

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
g=np.ones((2,3))

g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
#
h=np.empty((5,6))
print(h)

[[6.93866537e-310 4.66251394e-310 0.00000000e+000 0.00000000e+000
  2.41907520e-312 5.02034658e+175]
 [1.38614721e-047 6.43368488e-057 8.97492630e-067 5.39462569e-062
  1.47763641e+248 1.16096346e-028]
 [7.69165785e+218 1.35617292e+248 1.38501813e+006 3.89114840e-033
  2.35485024e-047 1.91858123e+030]
 [4.26582261e-096 6.32299154e+233 6.48224638e+170 5.22411352e+257
  5.74020278e+180 8.37174974e-144]
 [1.41529402e+161 9.16651763e-072 4.52743858e+097 4.43084405e-062
  3.42242415e+126 6.92566139e-310]]


In [40]:
I=np.arange(15)
print(I)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [42]:
#arange(start, end, step) can be used like this 
J=np.arange(5,50,5)
print(J)

[ 5 10 15 20 25 30 35 40 45]


In [43]:
k=np.arange(0,2,.3)
print(k)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [44]:
L=np.arange(.1, 3.5,.2)
print(L)

[0.1 0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3]


In [48]:
#using of linspace 
from numpy import pi
m=np.linspace(0,2,9) # means 9 numbers from 0 to 2 
print(m)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [50]:
x=np.linspace(0,2*pi,100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [52]:
#Bonus
f=np.sin(x)
print(f)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769