In [42]:
# basic Operations as per mentioned in README
import numpy as np
a=np.array([(12,15,17),(20,25,30)])
print(a)

[[12 15 17]
 [20 25 30]]


In [7]:
b=np.array([(10,18,15),(15,20,25)])

In [8]:
a-b

array([[ 2, -3,  2],
       [ 5,  5,  5]])

In [11]:
c=np.array([(1,2.5,3),(2,4,8)])

In [12]:
c**2

array([[ 1.  ,  6.25,  9.  ],
       [ 4.  , 16.  , 64.  ]])

In [13]:
a+c

array([[13. , 17.5, 20. ],
       [22. , 29. , 38. ]])

In [14]:
a+b

array([[22, 33, 32],
       [35, 45, 55]])

In [15]:
a/b

array([[1.2       , 0.83333333, 1.13333333],
       [1.33333333, 1.25      , 1.2       ]])

In [17]:
a**c

array([[1.20000000e+01, 8.71421253e+02, 4.91300000e+03],
       [4.00000000e+02, 3.90625000e+05, 6.56100000e+11]])

In [18]:
a<b

array([[False,  True, False],
       [False, False, False]])

In [19]:
a>c

array([[ True,  True,  True],
       [ True,  True,  True]])

In [43]:
a.shape

(2, 3)

In [21]:
b.shape

(2, 3)

In [28]:
b=np.reshape(b,(3,2))

In [29]:
a@b

array([[ 685,  866],
       [1175, 1485]])

In [30]:
a.dot(b)

array([[ 685,  866],
       [1175, 1485]])

In [44]:
# *= and += are used to modify the existing array
a+=a

In [45]:
print(a)

[[24 30 34]
 [40 50 60]]


In [38]:
#Bonus
#a.fill(0)

In [46]:
print(a)

[[24 30 34]
 [40 50 60]]


In [47]:
a.sum() # Sum of all element

238

In [48]:
c.sum()

20.5

In [50]:
d=np.array([(1,1,1),(1,1,1)])

In [51]:
d.sum()

6

In [52]:
c.min()

1.0

In [53]:
c.max()

8.0

In [57]:
f=np.arange(6).reshape(2,3)

In [58]:
print(f)

[[0 1 2]
 [3 4 5]]


In [60]:
#sum of each column 
f.sum(axis=0)

array([ 3, 12])

In [61]:
#sum of each row
f.sum(axis=1)

array([ 3, 12])

In [62]:
f.min(axis=0)#min of each column

array([0, 1, 2])

In [63]:
f.min(axis=1) # min of each row

array([0, 3])

In [64]:
f.max(axis=0)#max of each column

array([3, 4, 5])

In [65]:
f.max(axis=1)# max of each row

array([2, 5])

In [75]:
g=np.arange(6).reshape(2,3)
g

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
g.cumsum(axis=1) #cumulative sum along each row

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [66]:
I=np.arange(3)

In [67]:
print(I)

[0 1 2]


In [68]:
np.exp(I)

array([1.        , 2.71828183, 7.3890561 ])

In [77]:
np.sqrt(I)

array([0.        , 1.        , 1.41421356])

In [78]:
np.add(g,I)

array([[0, 2, 4],
       [3, 5, 7]])