In [2]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a=np.arange(15).reshape(3,5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
a=a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
a.ndim

2

In [9]:
a.shape

(4, 5)

In [16]:
a.ndim

2

In [17]:
a.size

20

In [19]:
a.dtype

dtype('int64')

In [20]:
a.itemsize

8

In [21]:
a.data

In [22]:
type(a)

numpy.ndarray

In [23]:
b=np.array([6,7,8])

In [24]:
b

array([6, 7, 8])

In [25]:
type(b)

numpy.ndarray

In [26]:
b.size

3

In [27]:
b.ndim

1

In [28]:
b.itemsize

8

In [29]:
b.shape

(3,)

In [35]:
dir(np.shape)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']