In [1]:
import numpy as np
z=np.ones(4*1000000,np.float32)

In [2]:
z

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [6]:
z.size

4000000

In [3]:
z[...]=0

In [4]:
z

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [7]:
z.size

4000000

In [15]:
z=np.arange(9).reshape(3,3).astype(np.int16)
z


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [10]:
z.strides

(6, 2)

In [13]:
z.shape

(3, 3)

In [12]:
z.itemsize

2

In [18]:
z.strides

(6, 2)

In [27]:
v=z[0::1,0::1]

In [28]:
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [29]:
#len:
z=np.array([(0,2),(6,8)])

In [30]:
z

array([[0, 2],
       [6, 8]])

In [31]:
z.shape[0]

2

In [32]:
z.shape[1]

2

In [35]:
len(z)

2

In [36]:
z=np.zeros(9)

In [37]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
Z_view=z[:3]

In [39]:
Z_view

array([0., 0., 0.])

In [41]:
Z_view[...]=1 # Here what ever we are changing int to Z_view that is affecting to the base array means both Z and Z_View
#are pointing to the same location 

In [70]:
print(Z_view.base) # means result is view 

[1. 1. 1. 0. 0. 0. 0. 0. 0.]


In [42]:
print(z)

[1. 1. 1. 0. 0. 0. 0. 0. 0.]


In [43]:
z=np.zeros(9)

In [44]:
Z_Copy=z[[0,1,2]]

In [45]:
Z_Copy

array([0., 0., 0.])

In [47]:
Z_Copy[...]=1

In [48]:
Z_Copy

array([1., 1., 1.])

In [49]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
print(z.base) # means result is a copy 

None


In [54]:
#help(np.random.uniform)

In [55]:
z=np.random.uniform(0,1,(5,5))

In [56]:
z

array([[0.49114517, 0.85145578, 0.36428468, 0.40746518, 0.95053066],
       [0.28848604, 0.44551581, 0.61814581, 0.16724523, 0.38257836],
       [0.27747216, 0.17753754, 0.57496917, 0.17673643, 0.32995516],
       [0.08269642, 0.79790749, 0.88545514, 0.02525164, 0.42621082],
       [0.09258282, 0.28580815, 0.52186643, 0.05822768, 0.97187599]])

In [57]:
z.shape

(5, 5)

In [58]:
z.size

25

In [59]:
z1=z[:3,:] # Fancy Indexing 

In [60]:
z1

array([[0.49114517, 0.85145578, 0.36428468, 0.40746518, 0.95053066],
       [0.28848604, 0.44551581, 0.61814581, 0.16724523, 0.38257836],
       [0.27747216, 0.17753754, 0.57496917, 0.17673643, 0.32995516]])

In [61]:
z1.shape

(3, 5)

In [62]:
z2=z[[0,1,2],:]

In [63]:
z2

array([[0.49114517, 0.85145578, 0.36428468, 0.40746518, 0.95053066],
       [0.28848604, 0.44551581, 0.61814581, 0.16724523, 0.38257836],
       [0.27747216, 0.17753754, 0.57496917, 0.17673643, 0.32995516]])

In [71]:
#help(np.allclose) # Returns True if two arrays are element-wise equal within a tolerance

In [72]:
print(np.allclose(z1,z2))

True


In [73]:
print(z1.base is z)

True


In [74]:
print(z2.base is z)

False


In [76]:
print(z2.base is None)

True


In [78]:
help(np.base)

AttributeError: module 'numpy' has no attribute 'base'

In [80]:
Z1=np.arange(10)

In [81]:
Z2=Z1[1:-1:2]

In [82]:
Z1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
Z2

array([1, 3, 5, 7])

In [87]:
print(Z2.base is Z1) # means Z2 is a veiw of Z1 and can be expressed as Z1[start:stop:step]

True


In [88]:
Step=Z2.strides[0] // Z1.strides[0]

In [ ]:
print(Step)

### byte_bounds Method : Returns a pointer to the end point of the array

In [92]:
#help(np.byte_bounds)

In [95]:
np.byte_bounds(z1)[0]

45227344

In [96]:
offset_start=np.byte_bounds(z2)[0]-np.byte_bounds(z1)[0]

In [97]:
print(offset_start)

-2705024


In [98]:
Z1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
print(Z1[(1,2,3),])

[1 2 3]


In [106]:
#temorary copy
x=np.ones(10,dtype=np.int)
y=np.ones(10,dtype=np.int)

In [107]:
A=2*y+2*y # this type product should ve avaoided because it create a temporary copy

In [108]:
A

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

### Instead of that as mentioned just above we should used the product like below then No temporary array has been created

In [109]:
np.multiply(x,2,out=x)
np.multiply(y,2,out=y)
np.add(x,y,out=x)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])