In [3]:
#Indexing,Slicing and Iterating
import numpy as np
a=np.arange(6)**3
print(a)

[  0   1   8  27  64 125]


In [4]:
#indexing
a[0]

0

In [5]:
a[2]

8

In [6]:
#slicing
a[1:5]

array([ 1,  8, 27, 64])

In [7]:
print(a[0:4])

[ 0  1  8 27]


In [18]:
b=np.arange(10)**3
print(b)

[  0   1   8  27  64 125 216 343 512 729]


In [17]:
print(b[0:6:2])

[ 0  8 64]


In [20]:
b[:6:2] = -1000 # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000

In [21]:
print(b)

[-1000     1 -1000    27 -1000   125   216   343   512   729]


In [24]:
b[: : -1] #reverse

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [23]:
#Iterating
for i in b:
    print(i)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [25]:
# To be Continue from multidimension array Indexing, Slicing and Iterating