In [1]:
#1 
import numpy as np 

In [10]:
#2
print(np.__version__)
np.show_config()

1.15.4


In [12]:
#3
z=np.zeros(10)
z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
#4 Memory Size
s=z.size # size
I= z.itemsize 
bytes=s*I
print(bytes)



800


In [21]:

print("%d bytes" % (z.size *z.itemsize))

800 bytes


In [26]:
z1=np.zeros(10)
z1[4]=1
print(z1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
z2=np.arange(10,50)
print(z2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [30]:
z3=np.arange(10,50)
print(z3[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [32]:
z4=np.arange(9).reshape(3,3)
print(z4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10 Find the Indices of non Zero Element

In [33]:
z5=np.nonzero([1,2,0,0,4,0])
print(z5)

(array([0, 1, 4]),)


## 11. 3*3 Idendity Matrix



In [36]:
I2=np.eye(3)
print(I2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12.   3x3x3 with random values

In [42]:

z4=np.random.random((3,3,3))
print(z4)

[[[1.78918542e-01 4.11024857e-01 7.16441920e-01]
  [4.91694512e-04 3.36939863e-01 9.62174978e-01]
  [4.78630963e-01 2.17584816e-01 9.15926253e-01]]

 [[9.47479518e-01 4.89349080e-01 5.22990406e-02]
  [1.62774321e-01 1.01223927e-01 3.14454452e-02]
  [8.12949322e-01 7.66770296e-01 1.23781301e-01]]

 [[1.78265321e-01 9.64273589e-01 9.27843114e-01]
  [6.82445928e-01 1.30898815e-01 7.18287273e-01]
  [2.12933882e-01 4.44827989e-01 8.04365575e-01]]]


In [43]:
z5=np.random.random((10,10))
print(z5)

[[0.41243756 0.77014983 0.79768049 0.18279988 0.13058738 0.19403578
  0.13846197 0.54648745 0.83633609 0.28561154]
 [0.00668122 0.01366922 0.69801513 0.18657539 0.67690043 0.91140003
  0.72710555 0.50346342 0.60581436 0.38609026]
 [0.42724294 0.99219605 0.08880145 0.94927905 0.68117416 0.15559275
  0.99605888 0.23607797 0.93118261 0.00325027]
 [0.58726026 0.75804539 0.8110403  0.85552731 0.01823272 0.11831525
  0.7870608  0.53383559 0.45054025 0.5218514 ]
 [0.165091   0.06302165 0.87863469 0.38979058 0.11504017 0.25318953
  0.14274297 0.6570333  0.16124856 0.78263048]
 [0.41248417 0.01332341 0.77581102 0.65400259 0.56081817 0.68062004
  0.5510918  0.20556359 0.1858847  0.58432464]
 [0.07776358 0.02472407 0.47556075 0.9632773  0.30233635 0.02265651
  0.64226085 0.97790829 0.9614836  0.99241539]
 [0.42889982 0.73155235 0.52000034 0.52832463 0.53673281 0.64537704
  0.22442103 0.97328418 0.28181756 0.0786073 ]
 [0.01306235 0.34653954 0.42850426 0.53001349 0.02333703 0.61591638
  0.11681809

In [45]:
z5.max()

0.9960588763213177

In [46]:
z5.min()

0.0032502741013685776

In [51]:
Zmin,Zmax=z5.min(),z5.max() # To Be noted

In [52]:
print(Zmin,Zmax)

0.0032502741013685776 0.9960588763213177


## 14  Create a random vector of size 30 and find the mean value

In [54]:
Z6=np.random.random(30)
print(Z6)

[0.96300548 0.08846554 0.27897854 0.58062307 0.08791876 0.80089308
 0.64488165 0.73741357 0.60626277 0.51888511 0.25130583 0.42296964
 0.41495017 0.69126145 0.61445885 0.14708006 0.9243891  0.15395319
 0.89152355 0.42582669 0.24133064 0.21643911 0.88476066 0.39326609
 0.549096   0.06091464 0.77582529 0.81398674 0.49041945 0.6962903 ]


In [58]:
m=Z6.mean()
print(m)

0.5122458335693383


## 15 Create a 2d array with 1 on the border and 0 inside

In [71]:
Z7=np.ones((5,5)) # 1. Take any square Matrix of ones
print(Z7)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
Z7[1:-1,1:-1]=0   # 

In [73]:
print(Z7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 16. How to add a border (filled with 0's) around an existing array?


In [84]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=2,mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [85]:
#help(np.pad)

In [93]:
#dir(np.nan)

In [92]:
print(0 * np.nan)  # NaN not a number is used for missing number 
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# ## numpy.diagonal
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.



In [115]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# ## 18 Create a 5x5 matrix with values 1,2,3,4 just below the diagona

In [120]:
z=np.zeros((8,8),dtype=np.int)
print(z)
z[1::2,::2]=1
z[::2,1::2]=1
print("\n\n")
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 19. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [130]:
#help(np.ravel)

In [122]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [123]:
print(x)

[[1 2 3]
 [4 5 6]]


In [128]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [129]:
print(np.ravel(z))

[0 1 2 3 4 5 6 7 8]


#help(np.unravel_index)->  Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.

In [133]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 22 Normalize a 5x5 random matrix

In [137]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))

In [138]:
print(Z)

[[ 1.83008805  0.1267896  -0.4964341  -1.10429574  0.8964268 ]
 [-0.93670506 -1.58056318 -0.2527921  -1.46112348  0.87796277]
 [ 1.52821461 -0.50401473  0.02568609 -0.35362043 -0.45928992]
 [ 0.27660034 -0.10094561  0.89876268  1.2552571  -0.45698964]
 [-1.38306305  0.77318133 -1.5720419   1.27637699  0.89653258]]


In [140]:
#help(np.ubyte)

### 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product

In [142]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [143]:
z=np.ones((5,3))@np.ones((3,2))

In [144]:
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25 Given a 1D array, negate all elements which are between 3 and 8, in place

In [148]:
z=np.arange(11)
z[(3<z) & ( z<=8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [152]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [151]:
print(sum(range(5),-1))

9


In [167]:
" {0:9}is the food of gods".format("Ambrosia")

' Ambrosia is the food of gods'

In [154]:
help(format)

Help on built-in function format in module builtins:

format(value, format_spec='', /)
    Return value.__format__(format_spec)
    
    format_spec defaults to the empty string.
    See the Format Specification Mini-Language section of help('FORMATTING') for
    details.



In [ ]:
"{0:10} is the food of gods".format("Ambrosia")